# Generated by Django 4.2.16 on 2025-08-12 18:37

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('buyer', 'Acheteur'), ('seller', 'Vendeur'), ('delivery', 'Livreur')], default='buyer', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified_seller', models.BooleanField(default=False, help_text="Vendeur vérifié par l'admin")),
                ('seller_since', models.DateTimeField(blank=True, help_text='Date de début en tant que vendeur', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise")),
                ('business_description', models.TextField(blank=True, verbose_name="Description de l'entreprise")),
                ('business_address', models.TextField(blank=True, verbose_name="Adresse de l'entreprise")),
                ('business_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone professionnel')),
                ('business_email', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
                ('business_license', models.CharField(blank=True, max_length=100, verbose_name='Numéro de licence')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro fiscal')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='seller_profiles/', verbose_name='Photo de profil')),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='business_logos/', verbose_name="Logo de l'entreprise")),
                ('accepts_returns', models.BooleanField(default=True, verbose_name='Accepte les retours')),
                ('return_policy', models.TextField(blank=True, verbose_name='Politique de retour')),
                ('shipping_policy', models.TextField(blank=True, verbose_name='Politique de livraison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Profil actif')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil vendeur',
                'verbose_name_plural': 'Profils vendeurs',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='Adresse principale')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Téléphone')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Photo de profil')),
                ('description', models.TextField(blank=True, help_text='Décrivez votre boutique ou vos services.', verbose_name='Description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255, verbose_name="Ligne d'adresse 1")),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name="Ligne d'adresse 2")),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('is_default', models.BooleanField(default=False, verbose_name='Adresse par défaut')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.profile')),
            ],
        ),
    ]
